-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "rent_end_date" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "rent_start_date" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "token" DROP NOT NULL;
